---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: nginx
    image: "avinashsi/nginx:V1.2"
    imagePullPolicy: Always
    ports:
    - containerPort: 443
      name: https
      protocol: TCP
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: nginx-ssl-certs
      mountPath:  /etc/nginx/ssl/
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: nginx-conf
  - name: nginx-ssl-certs
    secret:
      secretName: tls-certificate

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: frontend
